#!/usr/bin/env python3
"""
Build Belgium Historical Waste Hall of Fame (top ~100).
Pain metrics match docs/proposal-radar/TAXPAYER_UNIT.md (unit_version 2).

Honesty rules:
- Never invent precision; use ranges + confidence.
- Rank by waste_priority (cost class × absurdity × waste purity), not pure vibes.
- cost_mid is the figure used for pain columns (public € burden mid estimate).
- Distinguish full project cost vs pure waste vs multi-year structural TE.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT_CSV = DATA / "historical_waste_hall.csv"
OUT_MD = ROOT / "historical_waste_hall_of_fame.md"

# Taxpayer unit v2 (same as proposal-radar)
TAX = 19_400.0
NET = 29_500.0
N_EMP = 4_850_000.0
GROSS = 48_912.0
WORK_MIN = 100_320.0
EUR_PER_MIN = GROSS / WORK_MIN


def cost_score(eur: float | None) -> float:
    if eur is None or eur <= 0:
        return 0.0
    if eur < 1e6:
        return 1.5
    if eur < 1e7:
        return 3.5
    if eur < 1e8:
        return 5.5
    if eur < 1e9:
        return 7.5
    return 9.5


def pain(c: float | None) -> dict[str, str]:
    if c is None:
        return {
            "pain_tax_fte": "",
            "pain_net_years": "",
            "pain_eur_per_employee": "",
            "pain_work_minutes": "",
        }
    return {
        "pain_tax_fte": f"{c / TAX:.1f}",
        "pain_net_years": f"{c / NET:.1f}",
        "pain_eur_per_employee": f"{c / N_EMP:.2f}",
        "pain_work_minutes": f"{c / N_EMP / EUR_PER_MIN:.2f}",
    }


def fmt_eur(n: float | None) -> str:
    if n is None:
        return "Unknown"
    if n >= 1e9:
        return f"€{n/1e9:.2f} bn"
    if n >= 1e6:
        return f"€{n/1e6:.1f} m"
    if n >= 1e3:
        return f"€{n/1e3:.0f} k"
    return f"€{n:.0f}"


def fmt_min(m: str) -> str:
    if not m:
        return "—"
    x = float(m)
    if abs(x) >= 60:
        h = x / 60
        if h >= 24:
            return f"{x:.0f} min (~{h/24:.1f} d)"
        return f"{x:.0f} min (~{h:.1f} h)"
    if abs(x) >= 1:
        return f"{x:.1f} min"
    return f"{x:.2f} min"


# Each row: id, name, era, level, type, category,
# cost_min, cost_mid, cost_max, cost_basis, absurdity, purity, confidence,
# sources, one_liner, notes
# cost_* in EUR; None if unquantified
RAW: list[tuple] = [
    # === MEGA STRUCTURAL / MULTI-YEAR (illustrative cumulative or peak package) ===
    (
        "hw_wage_subsidy_wedge",
        "Wage-subsidy / labour-tax wedge compensation stack (multi-year class)",
        "2000s–2020s",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        80e9,
        100e9,
        150e9,
        "Illustrative multi-year TCO class: NBB enterprise wage-subsidy block ~€16.7bn/yr (2023/24 order); 6–10y cumulative for ranking comparability — NOT pure waste; deadweight share unknown",
        7.0,
        4.0,
        "medium",
        "NBB enterprise subsidies series; DOGE lb_wage_subsidies_block",
        "Perpetual fiscal duct-tape for Europe’s highest labour tax wedge — the euro is real; how much is pure waste is the open fight.",
        "Steelman: high wedge needs offset. Waste claim is deadweight + complexity, not the whole envelope.",
    ),
    (
        "hw_company_cars_decade",
        "Company-car tax expenditure package (10y class)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        25e9,
        35e9,
        50e9,
        "FFS ~€3.1–5.2bn/yr package class × ~10y illustrative; congestion + wage distortion externalities extra",
        8.5,
        7.0,
        "strong",
        "FPS FFS inventories; FPB company-car notes; DOGE lb_company_cars*",
        "A fringe benefit that rewrote Belgian mobility, congestion and the wage bill — for decades.",
        "Reform path exists (cash-out / equalise BIK); political difficulty high.",
    ),
    (
        "hw_ffs_fossil_decade",
        "Federal fossil-fuel subsidy inventory (10y class)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        70e9,
        100e9,
        130e9,
        "FFS direct ~€10.8bn (2024) × ~10y illustrative; path varies; broad definition contested",
        7.0,
        5.0,
        "medium",
        "FPS 5th FFS inventory 2026; DOGE lb_ffs_direct_total",
        "Cheap fossil by tax design, then climate targets by other instruments — policy schizophrenia at scale.",
        "Not all FFS lines are pure waste; many are price-support for heating/industry.",
    ),
    (
        "hw_taxex_total_decade",
        "Federal tax expenditures total quantified (5–10y class)",
        "2018–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        150e9,
        200e9,
        280e9,
        "FPS inventory ~€39bn quantified (2023 class) × multi-year; many unquantified still; mega-aggregate not a single cut",
        5.0,
        3.0,
        "strong",
        "FPS tax expenditure inventory; DOGE lb_fed_taxex_total",
        "Parliament’s deviation from the tax code is larger than many ministries — and still incomplete.",
        "Map entry for scale; do not campaign as ‘€200bn pure waste’.",
    ),
    (
        "hw_bank_bailouts_2008_12",
        "Banking crisis public capital injections (Fortis/Dexia/KBC/Ethias stack)",
        "2008–2012",
        "federal+regions",
        "bailout",
        "financial_crisis",
        15e9,
        22e9,
        35e9,
        "Order-of-magnitude BE public capital: Fortis ~€9.4bn path; Dexia BE capital + Belfius €4bn buy; KBC fed+VL ~€7.5bn class; Ethias; guarantees separate contingent",
        8.0,
        6.0,
        "medium",
        "Wikipedia 2008–09 BE financial crisis; Social Watch bank rescue note; EC state-aid decisions",
        "Too-big-to-fail became a taxpayer balance-sheet event — twice for Dexia.",
        "Net fiscal cost after recoveries/dividends lower than gross injections; guarantees were huge contingent.",
    ),
    (
        "hw_dexia_belfius_path",
        "Dexia dismantling + Belfius nationalisation path",
        "2008–2012",
        "federal",
        "bailout",
        "financial_crisis",
        4e9,
        7e9,
        12e9,
        "BE share of multi-country Dexia rescues + €4bn Belfius purchase + residual holding losses class; FR/LU shares excluded",
        8.5,
        7.0,
        "medium",
        "EC Dexia decisions; federal buy of Dexia Bank Belgium 2011",
        "Municipal lender + French expansion = Belgian taxpayers holding the bag.",
        "Belfius later profitable for the state — net depends on exit valuation.",
    ),
    (
        "hw_primary_gap_multi",
        "Primary balance gap vs debt-stabilising path (multi-year class)",
        "2020s",
        "federal+GG",
        "fiscal_architecture",
        "structural_fiscal",
        80e9,
        100e9,
        140e9,
        "IMF/NBB class ~€15–20bn/yr primary gap × multi-year; not a ‘project’ — the meta-waste of structural deficit",
        6.0,
        5.0,
        "medium",
        "IMF Art. IV; NBB public finance; DOGE lb_primary_gap",
        "Interest and snowball: the silent multi-billion that funds past choices.",
        "Not illegal spending; opportunity cost of delayed consolidation.",
    ),
    (
        "hw_cheque_economy_decade",
        "Cheque economy pure waste (admin + restriction DWL) — NOT full face/TE",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        0.8e9,
        2.5e9,
        5e9,
        "THREE LAYERS (do not mix): (A) Face/wages ~€3.55bn/yr VIA 2024 = mostly OK compensation; (B) TE/parafiscal ~€1.07bn/yr CoA private meal 2024 = tax preference vs cash, mixed; (C) Pure waste = admin sandwich + issuer rents + restriction deadweight — ILLUSTRATIVE mid ~€0.15–0.35bn/yr → decade mid €2.5bn (Weak–Medium). Pain columns use (C) mid only. Eco-cheques TE still Unknown.",
        8.5,
        5.0,
        "medium",
        "Rekenhof DOC 56 0785/004; VIA via CoA; notes-middleman-systems.md; DOGE lb_cheque_economy",
        "Most of the billions are wages in scrip form — retarded is forced spend + admin, not lunch money itself.",
        "v2 honesty fix: lowered waste_purity 8→5; pain on pure-waste mid not TE×10. Full TE decade ~€11bn is system size, not incinerated euros. Default reform: cash wages / tax-neutral pay.",
    ),
    (
        "hw_eiwt_decade",
        "EIWT partial remittance bedrijfsvoorheffing package (10y class)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        30e9,
        40e9,
        50e9,
        "~€4.4bn/yr 2024 package × ~10y; night/shift/R&D clusters",
        7.0,
        5.0,
        "strong",
        "FPS taxex inventory; DOGE lb_eiwt_package",
        "Night-shift and R&D wage tax discounts at multi-billion scale — additionality rarely proven at that scale.",
        "Prefer base-rate reform over perpetual patchwork.",
    ),
    (
        "hw_gsc_vl_decade",
        "Flanders green electricity certificates (GSC) support path",
        "2005–2025",
        "Flanders",
        "subsidy",
        "energy_policy",
        8e9,
        12e9,
        18e9,
        "Recent ~€0.8–1.1bn/yr class; multi-year PV boom overcompensation + residual certificates; lifetime higher",
        8.0,
        7.0,
        "medium",
        "VREG/VEA series; DOGE lb_vl_gsc_support; Court of Audit PV notes",
        "Early PV boom locked in rich certificates; households paid via bills for decades.",
        "Steelman: learning-curve renewables; waste is overcompensation design.",
    ),
    (
        "hw_offshore_wind_lifetime",
        "Federal offshore wind production support (lifetime class)",
        "2010s–2030s",
        "federal",
        "subsidy",
        "energy_policy",
        8e9,
        12.7e9,
        18e9,
        "NBB ESA + CREG cash paths; lifetime estimate class ~€12.7bn historically cited in DOGE notes",
        6.0,
        5.0,
        "medium",
        "NBB subsidies; CREG; DOGE lb_offshore_wind_support",
        "Climate steelman is real; overprofit and contract design are the waste debate.",
        "Later PEZ tenders improve; first-wave contracts residual.",
    ),
    (
        "hw_nid_notioneel",
        "Notional interest deduction (NID) multi-year deadweight class",
        "2006–2018+",
        "federal",
        "tax_expenditure",
        "corporate_tax",
        15e9,
        30e9,
        50e9,
        "NID was multi-bn/yr at peak; multi-year sum highly uncertain after reforms; deadweight vs HQ attraction contested",
        7.5,
        6.0,
        "weak",
        "FPS taxex historical; academic literature on NID; EU state-aid scrutiny",
        "Paper equity interest deduction that became a European tax-planning magnet.",
        "Confidence weak on pure deadweight €; keep ranges wide.",
    ),
    (
        "hw_dual_federalism_overhead",
        "Institutional dualism overhead (multi-parliaments, dual PSB, dual PES, dual justice language)",
        "1990s–2020s",
        "multi",
        "overhead-federalism",
        "institutions",
        20e9,
        40e9,
        80e9,
        "Highly speculative multi-year opportunity cost of permanent dual structures; dual PSB alone ~€0.65bn/yr ordinary; full dualism larger",
        8.0,
        6.0,
        "weak",
        "DOGE lb_dual_psb; institutional cost studies (order-of-magnitude)",
        "Two of everything that speaks a language — democracy has a price tag that is never on one budget line.",
        "Not a call to abolish communities; score is about unmeasured overhead.",
    ),
    # === MEGA INFRASTRUCTURE (with overruns / weak CBA) ===
    (
        "hw_oosterweel",
        "Oosterweelverbinding (Antwerp ring completion) — cost explosion path",
        "2000s–2030s",
        "Flanders",
        "infrastructure",
        "transport_capex",
        7e9,
        12e9,
        14e9,
        "Path ~€7bn → ~€10bn construction → ~€13.6bn financial-model class (2026 Rekenhof/press); pure ‘waste’ = overrun + financing risk not full mobility benefit",
        7.0,
        5.0,
        "medium",
        "VRT/Rekenhof 2026 Oosterweel financing; Lantis model notes",
        "Necessary tunnel politics meets a bill that keeps climbing toward the grandchildren.",
        "Steelman: closes ring, cuts urban traffic. Waste claim is governance of cost/toll, not asphalt itself.",
    ),
    (
        "hw_metro3_bru",
        "Brussels Metro line 3 — +hundreds-% budget path / freeze",
        "2009–2020s",
        "Brussels",
        "infrastructure",
        "transport_capex",
        3e9,
        4.76e9,
        5.5e9,
        "Court of Audit / press path from <€1bn class to ~€4.76bn total; +477% cited in governance summaries; project frozen/partially redesigned",
        9.0,
        8.0,
        "strong",
        "Cour des comptes Metro 3; Brussels Times; governance.brussels dossier",
        "A north–south metro that spent like a moonshot before a single full line ran.",
        "Ridership need is steelman; delivery failure is the waste.",
    ),
    (
        "hw_gen_rer_bru",
        "Brussels RER/GEN suburban rail — decades of delay & partial delivery",
        "1990s–2020s",
        "federal+Brussels+regions",
        "infrastructure",
        "transport_capex",
        2e9,
        5e9,
        10e9,
        "Multi-decade programme; full original plan never delivered on time/budget; sunk + remaining envelope uncertain — Medium/Weak on total",
        8.0,
        7.0,
        "weak",
        "NMBS/Infrabel RER dossiers; Court of Audit historical notes",
        "The suburban rail everyone promised for a generation — still waiting at many platforms.",
        "Partial works useful; waste is delay + rework + political fragmentation.",
    ),
    (
        "hw_liege_tram",
        "Liège tramway — cost overrun + availability payments",
        "2010s–2020s",
        "Wallonia",
        "infrastructure",
        "transport_capex",
        0.8e9,
        1.2e9,
        1.5e9,
        "Original ~€558m class → higher with WAL top-ups; media ~€1.4bn incl. extensions; PPP availability ~€32m/yr to 2052",
        7.0,
        6.0,
        "medium",
        "Railway Gazette 2024; EIB/DIF notes; local press",
        "A modern tram bought with PPP premiums after classic Belgian cost shock.",
        "Tram may still beat buses long-run; waste is contract design + overrun.",
    ),
    (
        "hw_charleroi_mlc",
        "Charleroi light metro — half-built network, ghost branches",
        "1970s–2020s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        0.5e9,
        1.5e9,
        3e9,
        "Decades of construction; Châtelet branch unused for years; total historical cost poorly consolidated publicly — range wide",
        9.5,
        9.0,
        "weak",
        "Wikipedia MLC; Defossé GTI; RTBF JTI; TEC history",
        "Eight arms planned, ghost tunnels for decades — waffle-iron metro politics in concrete.",
        "Parts now useful; pure waste is unused segments + time-value.",
    ),
    (
        "hw_antwerp_premetro_ghost",
        "Antwerp premetro unused tunnels & stations (50y ghost class)",
        "1970s–2020s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        0.2e9,
        0.6e9,
        1.5e9,
        "km of tunnel + stations idle decades; original build cost era-francs hard to rebase; reactivation now spending extra — Weak on original €",
        9.0,
        8.5,
        "weak",
        "Premetro history; Pegasus plan; Group A reactivation 2025–27 notes",
        "Underground trams that waited half a century for passengers — and more money to finish.",
        "Some tunnels finally activating; capital sat idle for a generation.",
    ),
    (
        "hw_bru_metro_ghosts",
        "Brussels metro ghost stations / unused levels (Sainctelette, Louise −3, etc.)",
        "1970s–1990s",
        "Brussels",
        "infrastructure",
        "ghost_infra",
        50e6,
        200e6,
        500e6,
        "Multiple unused shells; no single official consolidated bill; Defossé/RTBF JTI documentation — Weak €",
        9.0,
        9.0,
        "weak",
        "fr.wiki GTI; Defossé; RTBF Journal des Travaux Inutiles",
        "Stations built for lines that never came — Belgium’s most photogenic fiscal ghosts.",
        "Iconic absurdity > precise euro; cultural hall-of-fame entry.",
    ),
    (
        "hw_liege_metro_tunnel",
        "Liège unused metro tunnel (La Batte / Saint-Léonard)",
        "1970s–1980s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        20e6,
        80e6,
        200e6,
        "1970s tunnel for a metro that never opened; storage use later; era cost rebased poorly",
        9.5,
        9.5,
        "weak",
        "Defossé; RTBF JTI Liège metro 1986",
        "A prototype metro car in a tunnel to nowhere — Walloon futurism paused forever.",
        "Classic GTI; small vs banks but perfect purity.",
    ),
    (
        "hw_smeerpijp",
        "Smeerpijp (Limburg–Antwerp industrial sewer never used)",
        "1960s–1970s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        30e6,
        100e6,
        300e6,
        "107 km dual pipe never commissioned; era cost unknown — Weak rebased €",
        10.0,
        10.0,
        "weak",
        "Defossé; RTBF JTI Smeerpijp 1991",
        "A 107 km pollution pipe that never carried a drop — purity score: perfect 10.",
        "Possibly the purest boondoggle on the list.",
    ),
    (
        "hw_fyra_v250",
        "Fyra / V250 high-speed train fiasco (BE share of write-downs)",
        "2000s–2010s",
        "federal",
        "procurement",
        "rail_rolling_stock",
        100e6,
        250e6,
        500e6,
        "AnsaldoBreda V250 failure NL+BE; NMBS write-downs + replacement paths; BE share uncertain vs NS",
        9.5,
        9.0,
        "weak",
        "NMBS/NS Fyra parliamentary inquiries; press write-off series",
        "High-speed trains that could not handle winter — write-offs at TGV prices.",
        "NL cost larger; BE still ate real cash and delay.",
    ),
    (
        "hw_diabolo",
        "Diabolo rail link to Brussels Airport — surcharge model & cost",
        "2000s–2010s",
        "federal",
        "infrastructure",
        "transport_capex",
        0.5e9,
        0.8e9,
        1.2e9,
        "PPP-style airport rail; passenger surcharge funds debt; total project ~€0.5–1bn class depending on perimeter",
        6.0,
        4.0,
        "medium",
        "Infrabel/NMBS Diabolo dossiers; National Bank notes",
        "Useful airport rail paid forever via ticket surcharge — steelman works, opacity remains.",
        "Not pure waste; on list for financing design + lock-in.",
    ),
    (
        "hw_nmbs_ict_multi",
        "NMBS multi-year ICT / punctuality programme overruns (cluster)",
        "2000s–2020s",
        "federal",
        "procurement",
        "it_failure",
        0.3e9,
        0.8e9,
        2e9,
        "Cluster of delayed ticketing, planning, customer IT; no single consolidated public TCO — Weak",
        8.0,
        7.0,
        "weak",
        "Court of Audit NMBS ICT reports (various years); parliamentary Qs",
        "Railway software that arrives after the timetable it was meant to fix.",
        "Core ops not waste; IT delivery is.",
    ),
    (
        "hw_i_police",
        "i-Police federal police digitalisation failure",
        "2019–2026",
        "federal",
        "procurement",
        "it_failure",
        76e6,
        150e6,
        300e6,
        "Documented invoices ~€76m class; some press argue hundreds of millions total programme; litigation ongoing",
        9.5,
        9.5,
        "strong",
        "Brussels Times 2026; VRT/Nieuwsblad 2026; Tweakers; police claim vs Sopra Steria",
        "€76m+ for a police IT system that never truly worked — then lawyers.",
        "Strong on invoiced floor; upper bound disputed.",
    ),
    (
        "hw_justitie_it_cluster",
        "Justice IT mega-projects cluster (Phoenix/Cheops and successors)",
        "2000s–2020s",
        "federal",
        "procurement",
        "it_failure",
        100e6,
        400e6,
        1e9,
        "Decades of justice digitalisation failures; fragmented public totals — Medium/Weak",
        9.0,
        8.5,
        "weak",
        "Rekenhof justice IT reports; parliamentary history",
        "Courts still drowning in paper after successive ‘once-and-for-all’ IT reboots.",
        "Human cost (case delay) larger than cash alone.",
    ),
    (
        "hw_antwerp_courthouse",
        "Antwerp new courthouse (Gerechtsgebouw) cost overruns",
        "2000s–2010s",
        "federal",
        "infrastructure",
        "buildings",
        200e6,
        400e6,
        600e6,
        "Iconic Rogers Stirk Harbour design; large overrun vs original envelope (press/parliamentary history) — Medium",
        7.5,
        6.0,
        "medium",
        "Federal buildings agency history; press archive on Antwerp law courts",
        "A postcard courthouse that cost like a small metro line.",
        "Building is used; waste is overrun + procurement model.",
    ),
    (
        "hw_berlaymont_asbestos",
        "Berlaymont asbestos renovation (EU Commission HQ) — BE/EU shared path",
        "1990s–2000s",
        "multi/EU",
        "infrastructure",
        "buildings",
        0.5e9,
        0.8e9,
        1.2e9,
        "Multi-year closure & renovation classic overrun story; BE/EU financing mix — Medium",
        7.0,
        5.0,
        "medium",
        "EU/BE historical accounts; press on Berlaymont renovation",
        "The Commission’s HQ sat empty while asbestos and invoices piled up.",
        "Not pure BE bill; included for shared capital history.",
    ),
    (
        "hw_neo_heysel",
        "NEO / Heizel redevelopment delays & redesigns",
        "2010s–2020s",
        "Brussels",
        "infrastructure",
        "urban_dev",
        0.5e9,
        1.5e9,
        3e9,
        "Ambition multi-bn urban project; repeated redesign; sunk studies + partial works — Weak mid",
        7.5,
        6.5,
        "weak",
        "Brussels regional dossiers; press NEO Heizel",
        "Expo site dreams that keep reinventing the masterplan.",
        "Some public value possible; process waste high.",
    ),
    (
        "hw_strepy_thieu",
        "Strépy-Thieu boat lift — mega engineering, thin traffic",
        "1980s–2000s",
        "Wallonia",
        "infrastructure",
        "waterways",
        0.4e9,
        0.6e9,
        0.9e9,
        "One of world’s tallest lifts; long build; traffic below 1960s industrial forecasts; tourism partially salvages",
        8.0,
        7.0,
        "medium",
        "Hidden Monuments; SPW; historical canal modernisation files",
        "A cathedral of hydraulic engineering for a canal that never filled with barges.",
        "Iconic; utility disputed; tourism co-benefit.",
    ),
    (
        "hw_ronquieres",
        "Ronquières inclined plane — oversized for realised traffic",
        "1960s–1970s",
        "Wallonia",
        "infrastructure",
        "waterways",
        100e6,
        250e6,
        500e6,
        "Replaces 16 locks; traffic forecasts optimistic; era cost rebased Weak",
        7.5,
        7.0,
        "weak",
        "Hidden Monuments; canal history",
        "Sixteen locks replaced by a machine waiting for missing barges.",
        "Still operates; capacity underused vs design.",
    ),
    (
        "hw_godsheide_bridge",
        "Godsheide cable-stayed bridge (local traffic only)",
        "1970s–1980s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        20e6,
        50e6,
        120e6,
        "Largest BE cable-stayed bridge for a road that never became the planned expressway — Weak €",
        9.0,
        9.0,
        "weak",
        "fr.wiki GTI; Defossé",
        "Belgium’s grandest cable-stayed bridge… for neighbourhood traffic.",
        "Pure GTI classic.",
    ),
    (
        "hw_varsenare_bridges",
        "Varsenare ghost motorway bridges (demolished 2012)",
        "1970s–2010s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        5e6,
        15e6,
        40e6,
        "Two bridges for Calais–Zeebrugge motorway never built; demolished — Weak €",
        9.5,
        9.5,
        "weak",
        "Defossé; Focus WTV demolition",
        "Bridges over a railway to a highway that never arrived — then dynamite.",
        "Perfect absurdity, modest cash.",
    ),
    (
        "hw_neerpede_a9",
        "Neerpede / A9 ghost interchange earthworks",
        "1970s",
        "Brussels/Flanders",
        "infrastructure",
        "ghost_infra",
        10e6,
        40e6,
        100e6,
        "Massive interchange for abandoned A9; some mounds later leisure (Yéti Ski) — Weak €",
        9.0,
        8.5,
        "weak",
        "Defossé; wegen-routes.be A9",
        "Ski on the ruins of a motorway that politics killed — after earthworks.",
        "Partial reuse softens purity slightly.",
    ),
    (
        "hw_drogenbos_exchange",
        "Drogenbos partial ring exchange (half-demolished)",
        "1970s–1990s",
        "Brussels",
        "infrastructure",
        "ghost_infra",
        10e6,
        30e6,
        80e6,
        "Partial south ring works never completed; some bridges demolished — Weak €",
        8.5,
        8.5,
        "weak",
        "Defossé; R0 history",
        "Ring pieces built, then torn down — urban planning as temporary sculpture.",
        "Classic Brussels ring politics.",
    ),
    (
        "hw_machelen_interchange",
        "Machelen interchange unused ramps (later TGV partial use)",
        "1970s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        20e6,
        60e6,
        150e6,
        "E19–R0 monster interchange; part unused for decades; some later HSL use — Medium/Weak",
        8.0,
        7.0,
        "weak",
        "Defossé; Diabolo/HSL history",
        "A cloverleaf for a motorway into Brussels that never punched through.",
        "Partial later use reduces pure-waste score.",
    ),
    (
        "hw_n54_ghost",
        "N54 Charleroi–Maubeuge unfinished dual carriageway stubs",
        "1970s–1980s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        10e6,
        40e6,
        100e6,
        "Two stubs, unused bridge under N40 — Weak €",
        9.0,
        9.0,
        "weak",
        "Defossé; fr.wiki GTI",
        "A border motorway that ends in the middle of nowhere — twice.",
        "Waffle-iron cross-border ambition.",
    ),
    (
        "hw_heppignies_exchange",
        "Heppignies oversized exchange to a roundabout in fields",
        "1970s–1980s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        5e6,
        20e6,
        50e6,
        "Half-cloverleaf for missing fourth arm — Weak €",
        9.0,
        9.0,
        "weak",
        "fr.wiki GTI",
        "Motorway geometry designed for a fourth arm that is a field.",
        "Textbook GTI photo op.",
    ),
    (
        "hw_arquennes_bridge",
        "Arquennes bridge for Nivelles–Gouy ghost motorway",
        "1970s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        5e6,
        15e6,
        40e6,
        "Bridge over A54 slip for missing link — Weak €",
        9.0,
        9.0,
        "weak",
        "fr.wiki GTI",
        "A bridge ready for cars that never got a road.",
        "GTI classic.",
    ),
    (
        "hw_ypres_comines_canal",
        "Ypres–Comines canal incomplete (1864–1912)",
        "1860s–1910s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        5e6,
        20e6,
        80e6,
        "19th-c canal never joined; Hollebeke collapse; era francs → modern € speculative",
        8.5,
        9.0,
        "weak",
        "fr.wiki canal; GTI list",
        "Half a century of digging that never connected the water.",
        "Historical; opportunity cost in period labour.",
    ),
    (
        "hw_bernistap_tunnel",
        "Bernistap canal tunnel (Meuse–Moselle dream, 1828–1831)",
        "1820s–1830s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        2e6,
        10e6,
        40e6,
        "Interrupted by Belgian independence; half-bored — Weak rebased €",
        8.0,
        9.0,
        "weak",
        "fr.wiki Tunnel de Bernistap",
        "William I’s canal tunnel stopped by a revolution — and never restarted.",
        "Geopolitical abort more than mismanagement.",
    ),
    (
        "hw_etterbeek_hospital",
        "Etterbeek hospital — built 1982, closed after months",
        "1980s",
        "Brussels",
        "infrastructure",
        "buildings",
        30e6,
        80e6,
        150e6,
        "New hospital fused away almost immediately — Weak rebased €",
        9.5,
        9.5,
        "weak",
        "Defossé; RTBF JTI",
        "Opened the champagne, then the merger memo — hospital-shaped waste.",
        "Extreme purity classic.",
    ),
    (
        "hw_rayon_soleil",
        "Hôpital Rayon de Soleil (Montigny) — empty decades + fraud affair",
        "1980s–2010s",
        "Wallonia",
        "infrastructure",
        "buildings",
        20e6,
        60e6,
        120e6,
        "35,000 m² empty ~26y; fraud dimension — Weak €",
        9.5,
        9.5,
        "weak",
        "Defossé; RTBF JTI",
        "A hospital shell and a crime file — public money and private capture.",
        "Scandal + GTI hybrid.",
    ),
    (
        "hw_thuin_internat",
        "Thuin Athénée boarding school complex offset by 1.5 m",
        "1970s–1980s",
        "FWB",
        "infrastructure",
        "buildings",
        5e6,
        15e6,
        40e6,
        "Built off-grid by 1.5 m; unfinished; FWB left holding shell — Weak €",
        10.0,
        10.0,
        "weak",
        "RTBF JTI Thuin 2011",
        "Offset the building by a metre and a half — then ran out of money to connect anything.",
        "Comedy-grade purity 10.",
    ),
    (
        "hw_wtc_north_quarter",
        "Brussels North Quarter / WTC towers — unfinished urban plan",
        "1960s–1990s",
        "Brussels",
        "infrastructure",
        "urban_dev",
        0.5e9,
        1.5e9,
        3e9,
        "Manhattanisation of popular neighbourhood; 8 towers planned, 3 WTC + later towers; social cost huge, public € mix private — Weak",
        8.5,
        7.0,
        "weak",
        "Defossé; RTBF JTI quartier Nord",
        "Bulldoze a neighbourhood for eight towers — deliver three and a windswept esplanade.",
        "Mix of public planning failure and private capital.",
    ),
    (
        "hw_sabena_collapse",
        "Sabena bankruptcy — public shareholding losses + social fallout",
        "1990s–2001",
        "federal",
        "soe_failure",
        "transport_soe",
        0.5e9,
        1.5e9,
        3e9,
        "State airline collapse; public capital loss + unemployment support; Swissair litigation recovered little — Medium/Weak",
        8.0,
        7.0,
        "weak",
        "Federal Planning Bureau Sabena eval; Wikipedia Sabena faillissement",
        "National flag carrier to Europe’s biggest corporate failure — 7,500 jobs later.",
        "Global aviation shock + governance; not pure theft.",
    ),
    (
        "hw_bpost_press",
        "bpost press distribution concession (multi-year before 2027 end)",
        "2000s–2020s",
        "federal",
        "subsidy",
        "media_postal",
        0.8e9,
        1.5e9,
        2.5e9,
        "~€125m/yr class multi-year; ending 2027 rare cut path",
        6.5,
        6.0,
        "strong",
        "NBB; government phase-out; DOGE lb_bpost_press_concession",
        "Paying a postal monopoly to deliver newspapers — until finally not.",
        "Rare sunset; still multi-year cash burned.",
    ),
    (
        "hw_dual_psb_decade",
        "Dual public broadcasters VRT + RTBF (10y ordinary dots class)",
        "2015–2025",
        "multi",
        "subsidy",
        "institutions",
        5e9,
        6.5e9,
        8e9,
        "~€0.65bn/yr ordinary dual PSB × 10y; each may be justified alone — dualism is the waste claim",
        6.0,
        5.0,
        "strong",
        "DOGE lb_dual_psb; community budgets",
        "Two full public broadcasters for 11 million people — linguistic federalism on screen.",
        "Not ‘abolish culture’; score dual overhead.",
    ),
    (
        "hw_publifin_nethys",
        "Publifin / Nethys / Enodia intercommunale capture scandals",
        "2010s",
        "Wallonia",
        "governance_scandal",
        "local_capture",
        50e6,
        200e6,
        500e6,
        "Director fees, opacity, political capture; direct cash vs opportunity cost hard to separate — Weak mid",
        9.0,
        8.5,
        "weak",
        "Parliamentary inquiries; press Publifin/Nethys",
        "Intercommunales as political ATM — energy dividends and director seats.",
        "Governance failure > single project invoice.",
    ),
    (
        "hw_samusocial",
        "Samusocial Brussels mismanagement scandal",
        "2010s",
        "Brussels",
        "governance_scandal",
        "local_capture",
        5e6,
        20e6,
        50e6,
        "Housing/allowance scandal for directors while serving homeless — cash small, trust cost huge",
        9.5,
        9.0,
        "medium",
        "Press/court Samusocial; regional follow-up",
        "A homeless charity with luxury housing for the wrong people.",
        "Moral absurdity off the charts.",
    ),
    (
        "hw_dioxin_crisis",
        "1999 dioxin crisis — farm slaughter, export ban, political collapse",
        "1999",
        "federal",
        "crisis_cost",
        "food_safety",
        0.5e9,
        1.5e9,
        3e9,
        "Compensation, destroyed livestock, export losses, government fall — range includes private losses; public share Medium",
        8.0,
        6.0,
        "weak",
        "Wikipedia Dioxine crisis; OECD/agri estimates historical",
        "Contaminated feed, empty shelves, a government that fell — food safety as systemic failure.",
        "Not a vanity project; regulatory failure costs.",
    ),
    (
        "hw_agusta_scandal",
        "Agusta / Dassault helicopter & aircraft kickback scandal",
        "1980s–1990s",
        "federal",
        "procurement_corruption",
        "defence",
        50e6,
        200e6,
        500e6,
        "Defence procurement corruption; political careers ended; pure cash vs counterfactual aircraft unclear",
        9.0,
        8.0,
        "weak",
        "Agusta scandal history; court records summaries",
        "Helicopters with a side order of party financing — NATO ally meets Italian envelopes.",
        "Corruption premium hard to €-isolate.",
    ),
    (
        "hw_nh90_a400m",
        "NH90 / A400M defence programme delays & extra costs (BE share)",
        "2000s–2020s",
        "federal",
        "procurement",
        "defence",
        0.3e9,
        0.8e9,
        1.5e9,
        "European co-op programmes chronic delay; BE share of overruns Medium/Weak",
        7.0,
        6.0,
        "weak",
        "Defence parliamentary docs; NAO-style BE notes",
        "Aircraft that arrive late, rare, and expensive — European industrial policy in uniform.",
        "Capability eventually real; waste is delay/cost.",
    ),
    (
        "hw_f35_path",
        "F-35 replacement path — lifecycle cost lock-in debate",
        "2018–2040s",
        "federal",
        "procurement",
        "defence",
        4e9,
        6e9,
        10e9,
        "Acquisition + lifecycle class multi-bn; not pure waste — opportunity cost vs alternatives contested",
        5.0,
        3.0,
        "medium",
        "Defence Strategic Vision; parliamentary fighter debates",
        "Deterrence steelman vs sticker shock — on the list as fiscal lock-in, not automatic clown.",
        "Low purity: core security good if delivered.",
    ),
    (
        "hw_nuclear_phaseout_policy",
        "Nuclear phase-out / extension stop-start policy costs",
        "2003–2020s",
        "federal",
        "energy_policy",
        "energy_policy",
        2e9,
        8e9,
        20e9,
        "Policy volatility: provisions, Engie negotiations, capacity mechanisms, import dependency — highly contested range",
        8.0,
        6.0,
        "weak",
        "CREG; FPS Economy; Engie agreements; FPB energy notes",
        "Vote to close reactors, then pay to keep them — energy policy as ping-pong.",
        "Climate/security trade-offs real; process waste huge.",
    ),
    (
        "hw_energy_crisis_blanket",
        "2021–23 energy-crisis blanket support (poor targeting share)",
        "2021–2023",
        "federal+regions",
        "subsidy",
        "crisis_fiscal",
        5e9,
        12e9,
        20e9,
        "Total energy support packages multi-bn; pure waste = non-targeted share only — Medium/Weak split",
        7.0,
        5.0,
        "weak",
        "NBB/FPB crisis support tallies; FPS",
        "Price shock real; writing cheques to everyone is the lazy instrument.",
        "Steelman: social peace; waste is untargeted design.",
    ),
    (
        "hw_solar_pv_vl_boom",
        "Flanders residential PV over-subsidy boom (certificates era)",
        "2009–2015",
        "Flanders",
        "subsidy",
        "energy_policy",
        2e9,
        4e9,
        8e9,
        "Subset of GSC story focused on residential boom overcompensation; overlaps hw_gsc_vl_decade — do not full-sum",
        8.5,
        8.0,
        "medium",
        "VREG historical certificate prices; Court of Audit",
        "Rooftop gold rush with guaranteed certificates — non-PV households paid.",
        "Overlaps GSC row; ranking uses this as highlight chapter.",
    ),
    (
        "hw_wal_pv_certificates",
        "Walloon PV / green certificate overcompensation path",
        "2008–2018",
        "Wallonia",
        "subsidy",
        "energy_policy",
        1.5e9,
        3e9,
        6e9,
        "CWAPE/CWaPE certificate burdens; multi-year household bill impact — Medium",
        8.5,
        8.0,
        "medium",
        "CWaPE reports; WAL energy policy reviews",
        "Same movie as Flanders, French-speaking soundtrack, same bill on the meter.",
        "Design twin of VL boom.",
    ),
    (
        "hw_maribel_decade",
        "Maribel social funds wage subsidies (10y class)",
        "2015–2025",
        "federal",
        "subsidy",
        "structural_fiscal",
        10e9,
        15e9,
        20e9,
        "~€1.5bn/yr class × 10y; care jobs steelman; additionality open",
        6.0,
        4.0,
        "strong",
        "NBB; DOGE lb_maribel_social_funds",
        "Non-market employment subsidies at billion scale — FTE outcomes under-published.",
        "Not pure waste; transparency gap is.",
    ),
    (
        "hw_dienstencheques_decade",
        "Service vouchers (dienstencheques) multi-year fiscal cost",
        "2004–2020s",
        "federal+regions",
        "subsidy",
        "structural_fiscal",
        15e9,
        25e9,
        40e9,
        "Large recurring labour-market instrument; employment vs deadweight debated; multi-year TCO class",
        6.5,
        5.0,
        "medium",
        "IDEA/FPB evaluations; regional budgets",
        "Formalise domestic work with a fiscal booster rocket — forever.",
        "Steelman: reduce black labour; waste is permanent subsidy intensity.",
    ),
    (
        "hw_company_cars_fuel_cards",
        "Fuel cards PIT+SSC tax expenditure (multi-year with company cars)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        4e9,
        7e9,
        10e9,
        "FFS fuel cards ~€0.66bn 2024 × ~10y; stacks with company cars",
        8.5,
        8.0,
        "strong",
        "FPS FFS; DOGE lb_fuel_cards",
        "Free fuel as wage — congestion externality included free of charge.",
        "Companion to company-car package.",
    ),
    (
        "hw_vat_horeca_decade",
        "VAT reduced rate horeca (multi-year taxex)",
        "2010s–2020s",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        8e9,
        12e9,
        15e9,
        "~€1.2bn/yr class × ~10y; employment RCT thin",
        6.0,
        5.0,
        "strong",
        "FPS taxex; DOGE lb_vat_horeca",
        "Cheaper steak frites by statute — sector lobby with a VAT code.",
        "Steelman: labour-intensive sector; waste is untargeted permanence.",
    ),
    (
        "hw_exc_heatoil_decade",
        "Heating gasoil excise preference (multi-year FFS)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        12e9,
        18e9,
        22e9,
        "~€1.8bn/yr 2024 class × ~10y; not progressive",
        8.0,
        7.0,
        "strong",
        "FPS FFS; DOGE lb_exc_heatoil",
        "Cheap heating oil by design while climate policy points the other way.",
        "Social heating need real; instrument is blunt.",
    ),
    (
        "hw_kerosene_decade",
        "International aviation kerosene excise exemption (10y)",
        "2015–2025",
        "federal",
        "tax_expenditure",
        "structural_fiscal",
        5e9,
        7e9,
        9e9,
        "FFS ~€0.7bn/yr rising × 10y; Chicago Convention lock-in",
        8.0,
        7.5,
        "strong",
        "FPS FFS kerosene tables; DOGE lb_ffs_kerosene_air",
        "Fly tax-free fuel while trains pay full freight — 1940s law meets 2020s climate.",
        "EU coordination required; BE alone limited.",
    ),
    (
        "hw_facultative_subsidies",
        "Federal facultative discretionary subsidies opacity (multi-year)",
        "2015–2025",
        "federal",
        "subsidy",
        "structural_fiscal",
        5e9,
        9e9,
        12e9,
        "~€0.9bn/yr envelope × 10y; many justified — opacity is the DOGE issue",
        8.0,
        6.0,
        "strong",
        "BOSA toelagenregister; DOGE lb_fed_facultative_subsidies",
        "Ministers’ discretionary chequebook — public money without a public shopping list.",
        "Cut path exists (−200m narratives); L5 still weak.",
    ),
    (
        "hw_vl_carbon_leakage",
        "Flanders CIE carbon-leakage compensation (multi-year)",
        "2010s–2020s",
        "Flanders",
        "subsidy",
        "energy_policy",
        1.5e9,
        2.5e9,
        4e9,
        "~€0.25bn/yr class path; ~40 firms; invest audits delayed",
        6.0,
        5.0,
        "strong",
        "VLAIO/FIO; DOGE lb_vl_carbon_leakage_cie",
        "Pay heavy industry for EU-ETS power costs — additionality on a promise.",
        "Steelman EU CIE; L5 names FOI.",
    ),
    (
        "hw_actiris_growth",
        "Actiris PES budget growth vs placement outcomes debate",
        "2005–2020s",
        "Brussels",
        "agency",
        "labour_market",
        3e9,
        5e9,
        8e9,
        "Current ~€0.65–0.69bn/yr; multi-year cumulative; headcount growth noted — not pure waste",
        6.0,
        4.0,
        "medium",
        "Actiris budgets; DOGE lb_actiris; Cour notes",
        "A PES that grew with unemployment — dual-market Brussels complexity real.",
        "Core service; efficiency claim is the waste angle.",
    ),
    (
        "hw_vdab_forem_dual",
        "Triple PES architecture (VDAB/FOREM/Actiris + federal layer)",
        "1980s–2020s",
        "multi",
        "overhead-federalism",
        "institutions",
        5e9,
        10e9,
        20e9,
        "Speculative multi-year dual/triple employment-service overhead vs single counterfactual — Weak",
        7.5,
        6.0,
        "weak",
        "Regional PES budgets; institutional analyses",
        "Three public employment services and still the activation maze.",
        "Language/federalism constraint; still cost.",
    ),
    (
        "hw_empty_public_estate",
        "Empty / underused public building stock (multi-year opportunity cost)",
        "2000s–2020s",
        "multi",
        "asset_waste",
        "assets",
        1e9,
        5e9,
        15e9,
        "No single register; opportunity cost of idle capital speculative — Weak",
        7.5,
        7.0,
        "weak",
        "Court of Audit building stock notes; regional inventories partial",
        "Public walls with no people — capital depreciation as quiet waste.",
        "Needs FOI/register campaign.",
    ),
    (
        "hw_social_housing_vacancy",
        "Social housing vacancy & renovation backlog costs",
        "2000s–2020s",
        "multi",
        "ops",
        "housing",
        1e9,
        3e9,
        8e9,
        "Vacant units + delayed reno while waiting lists grow; multi-year opportunity — Weak",
        8.0,
        7.0,
        "weak",
        "Regional housing companies reports; press vacancy series",
        "People on lists, empty flats in the stock — allocation failure as fiscal waste.",
        "Human cost primary.",
    ),
    (
        "hw_plan_oxygene",
        "Plan Oxygène Walloon municipal debt oxygen (borrowing for opex risk)",
        "2020s",
        "Wallonia",
        "ops",
        "local_finance",
        0.5e9,
        1.5e9,
        2e9,
        "Tranches hundreds of m€; requests toward ~€1.8bn class; structural opex risk",
        7.0,
        6.0,
        "medium",
        "DOGE lb_plan_oxygene_envelope; PW docs",
        "Oxygen for commune cashflow — risk of permanent life support.",
        "Stabilisation steelman; cliff 2027 risk.",
    ),
    (
        "hw_relance_vv_roi",
        "Vlaamse Veerkracht / RRF project ROI mixed bag (subset risk)",
        "2021–2026",
        "Flanders",
        "multi-year_commitment",
        "stimulus",
        1e9,
        2e9,
        4e9,
        "Programme larger; waste claim is low-ROI subset only — Weak split",
        6.0,
        5.0,
        "weak",
        "VL BO/relance docs; DOGE lb_relance_vv",
        "EU recovery money spent fast — additionality and CBA uneven.",
        "Not all waste; sunset + open list required.",
    ),
    (
        "hw_smaakhaven",
        "Smaakhaven food innovation campus subsidy (Radar clown classic)",
        "2020s",
        "Flanders",
        "subsidy",
        "vanity_project",
        30e6,
        38e6,
        50e6,
        "Public envelope ~€38m class analysed in Proposal Radar",
        8.5,
        8.0,
        "strong",
        "Proposal Radar prop_2022_smaakhaven_38m; press",
        "Food campus vibes with a fiscal bill you can taste in werkminuten.",
        "Small vs banks; high absurdity density.",
    ),
    (
        "hw_wassalon",
        "Het Wassalon gelijke-kansen vodcast (tiny cash, max absurdity)",
        "2020s",
        "Flanders",
        "subsidy",
        "vanity_project",
        0.2e6,
        0.8e6,
        1e6,
        "~€800k/3y class DOGE; annual ~€0.27m",
        9.5,
        9.0,
        "strong",
        "DOGE lb_vl_wassalon_podcast",
        "A podcast so equal-opportunity it made the waste leaderboard on pure vibes-per-euro.",
        "Honourable absurdity mention; not top by cash.",
    ),
    (
        "hw_interco_dividends",
        "Intercommunale dividend politics (energy/water) — soft capture",
        "1990s–2020s",
        "local",
        "soe_governance",
        "local_capture",
        2e9,
        5e9,
        10e9,
        "Dividends fund local politics; opportunity cost of inefficient utility governance speculative multi-year — Weak",
        8.0,
        6.5,
        "weak",
        "Publifin inquiry legacy; CREG/utility reports",
        "Your water bill elects a board you never heard of.",
        "Structural local-capture pattern.",
    ),
    (
        "hw_party_media_transfers",
        "Party / political-group / media-adjacent public transfers opacity",
        "1990s–2020s",
        "multi",
        "transfer",
        "politics",
        0.5e9,
        1.5e9,
        3e9,
        "Fragmented (dotations, media, foundations); multi-year opacity — Weak",
        8.5,
        7.0,
        "weak",
        "Parliament dotation rules; media subsidy debates",
        "Democracy needs parties; blank-cheque opacity does not.",
        "Transparency reform > abolish politics.",
    ),
    (
        "hw_awareness_campaigns",
        "Awareness campaigns with no behaviour-change evidence (cluster)",
        "2000s–2020s",
        "multi",
        "opex",
        "vanity_project",
        0.2e9,
        0.6e9,
        1.5e9,
        "Death by a thousand posters; multi-year cluster speculative — Weak",
        9.0,
        8.5,
        "weak",
        "DOGE seed board; various CoA notes",
        "Poster politics: if you can’t measure it, bill it to communications.",
        "High absurdity density.",
    ),
    (
        "hw_duplicate_it_portals",
        "Duplicate digital portals across governments (cluster)",
        "2000s–2020s",
        "multi",
        "procurement",
        "it_failure",
        0.5e9,
        1.5e9,
        4e9,
        "Same citizen service rebuilt N times; multi-year speculative — Weak",
        8.0,
        8.0,
        "weak",
        "DOGE seed board; BOSA digital notes",
        "My e-box, your e-box, their e-box — federalism as UX debt.",
        "Shared platforms are the cut proposal.",
    ),
    (
        "hw_training_vouchers",
        "Training vouchers / activation with weak job placement (cluster)",
        "2000s–2020s",
        "multi",
        "subsidy",
        "labour_market",
        2e9,
        5e9,
        10e9,
        "Attendance ≠ employment; multi-year cluster Medium/Weak",
        7.5,
        7.0,
        "weak",
        "PES evaluations; Rekenhof training notes",
        "Certificates of attendance sold as labour-market miracles.",
        "Pay for placement outcomes.",
    ),
    (
        "hw_early_exit_pensions",
        "Early labour-market exit & special pension schemes (multi-year)",
        "1980s–2020s",
        "federal",
        "entitlement",
        "structural_fiscal",
        30e9,
        60e9,
        100e9,
        "Structural early-exit culture cost; multi-decade fiscal — Medium/Weak on pure ‘waste’ vs social choice",
        8.0,
        6.0,
        "weak",
        "NBB/FPB pension notes; OECD ageing BE",
        "Retire early, bill the next cohort — special schemes as political glue.",
        "Reform path: close schemes, automatic adjusters.",
    ),
    (
        "hw_housing_supply_block",
        "Housing supply blocks + compensatory subsidies (policy package)",
        "1990s–2020s",
        "multi",
        "regulation+subsidy",
        "housing",
        10e9,
        30e9,
        80e9,
        "Scarcity rents + subsidy bill; counterfactual YIMBY savings speculative — Weak",
        9.0,
        7.0,
        "weak",
        "DOGE seed board; regional housing plans",
        "Cause the shortage, then subsidise the victims of the shortage.",
        "Mechanism classic; € highly model-dependent.",
    ),
    (
        "hw_permit_denseness",
        "Professional order / permit denseness entry barriers (deadweight)",
        "post-war–2020s",
        "multi",
        "regulation",
        "institutions",
        5e9,
        20e9,
        50e9,
        "OECD product-market regulation deadweight speculative multi-year — Weak",
        7.0,
        6.0,
        "weak",
        "OECD PMR; EU services directive BE implementation",
        "Need a stamp to compete — insiders smile, prices rise.",
        "Indirect waste; sunrise reviews.",
    ),
    (
        "hw_kortrijk_r8",
        "Kortrijk R8 ring incomplete for 50+ years",
        "1970s–2020s",
        "Flanders",
        "infrastructure",
        "ghost_infra",
        50e6,
        150e6,
        400e6,
        "Half-ring for decades; completion drip — Weak total historical",
        8.0,
        7.5,
        "weak",
        "Hidden Monuments dead-end viaduct; AWV history",
        "A ring road that never quite ringed — 50 years of temporary forever.",
        "Partial utility; completion still political.",
    ),
    (
        "hw_anvaing_n60",
        "N60 Anvaing unused four-lane embankment",
        "1970s–1980s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        5e6,
        20e6,
        50e6,
        "700m embankment + useless viaducts — Weak €",
        9.0,
        9.5,
        "weak",
        "Hidden Monuments unused four-lane road",
        "Four lanes of asphalt ambition ending in a ploughed field.",
        "GTI photo classic.",
    ),
    (
        "hw_strepy_dead_end_road",
        "Strépy dead-end four-lane road to a field",
        "1970s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        3e6,
        12e6,
        30e6,
        "Next to famous boat lift — irony included free — Weak €",
        9.5,
        9.5,
        "weak",
        "Hidden Monuments",
        "Next to a world-famous boat lift: a highway to a cabbage field.",
        "Pure GTI.",
    ),
    (
        "hw_hingeon_bridge",
        "Hingeon bridge from cul-de-sac to a field over E42",
        "1970s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        1e6,
        5e6,
        15e6,
        "Bridge over motorway to nowhere — Weak €",
        9.5,
        10.0,
        "weak",
        "fr.wiki GTI; RTBF ponts inutiles",
        "A bridge from a dead-end street to a field — over a motorway.",
        "Absurdist perfection.",
    ),
    (
        "hw_perwez_bridge",
        "Perwez bypass bridge unused; project buried 2019",
        "2010s",
        "Wallonia",
        "infrastructure",
        "ghost_infra",
        2e6,
        8e6,
        15e6,
        "Bridge built; bypass cancelled; +€6.7m would have been needed — Medium/Weak",
        9.0,
        9.0,
        "medium",
        "RTBF/RTL Perwez 2017–2019",
        "Build the bridge first, cancel the road later — modern GTI.",
        "Recent enough to still sting.",
    ),
    (
        "hw_lavoir_peronnes",
        "Péronnes coal washery — short life, long empty, then renovated empty",
        "1950s–2000s",
        "Wallonia",
        "infrastructure",
        "industrial_shell",
        10e6,
        40e6,
        100e6,
        "15 years operation; decades empty; public reno without reuse — Weak €",
        8.5,
        8.5,
        "weak",
        "RTBF JTI lavoir Péronnes",
        "Wash coal for 15 years, then renovate the ruin for nothing.",
        "Industrial heritage vs zombie spend.",
    ),
    (
        "hw_mirwart_castle",
        "Château de Mirwart — repeated failed public/private conversions",
        "1970s–2010s",
        "Wallonia",
        "infrastructure",
        "buildings",
        5e6,
        20e6,
        50e6,
        "Hotel school / luxury hotel dreams; public money and delays — Weak €",
        8.0,
        8.0,
        "weak",
        "RTBF JTI Mirwart",
        "A castle that refused every business plan thrown at it.",
        "Heritage hard; process waste real.",
    ),
    (
        "hw_dolimarts",
        "Centre des Dolimarts — asylum plan fail, then decay sale",
        "1960s–2010s",
        "federal",
        "infrastructure",
        "buildings",
        5e6,
        20e6,
        50e6,
        "Federal buy for asylum centre that never opened — Weak €",
        8.5,
        8.5,
        "weak",
        "RTBF JTI Dolimarts",
        "Buy a holiday camp for asylum seekers, do nothing, sell a wreck.",
        "Federal asset mismanagement vignette.",
    ),
    (
        "hw_simonis_stations",
        "Simonis / Pannenhuis stations closed then reopened decades later",
        "1980s–2010s",
        "federal",
        "infrastructure",
        "ghost_infra",
        10e6,
        40e6,
        100e6,
        "Built, closed 1984, reopened 2009/2015 — capital idle decades — Weak €",
        8.0,
        7.5,
        "weak",
        "Defossé; SNCB history",
        "Stations so useless they closed — then useful enough to reopen. Time-value still lost.",
        "Partial redemption lowers purity.",
    ),
    (
        "hw_justice_palais_bru",
        "Brussels Palace of Justice — endless renovation / scaffolding culture",
        "1980s–2020s",
        "federal",
        "infrastructure",
        "buildings",
        0.2e9,
        0.6e9,
        1.5e9,
        "Multi-decade scaffolding meme; cumulative reno bills fragmented — Weak",
        8.5,
        7.0,
        "weak",
        "Federal buildings; press palais justice scaffolding",
        "Europe’s largest law courts, permanently under tarpaulin.",
        "Heritage + bureaucracy; still a fiscal drip.",
    ),
    (
        "hw_credendo_contingent",
        "Credendo export-credit cover capacity (contingent public risk)",
        "2000s–2020s",
        "federal",
        "contingent_liability",
        "financial_risk",
        5e9,
        15e9,
        33e9,
        "Cover capacity class up to ~€33bn contingent — not cash spent; expected loss much lower",
        6.0,
        4.0,
        "medium",
        "DOGE lb_credendo_cover_capacity_33bn; annual reports",
        "Taxpayers as silent co-insurer of export risk — fine print in the billions.",
        "Not spent cash; still public risk capital.",
    ),
    (
        "hw_excess_profit_rulings",
        "Excess profit tax rulings (EU state-aid recovery saga)",
        "2005–2020s",
        "federal",
        "tax_ruling",
        "corporate_tax",
        0.5e9,
        1e9,
        2e9,
        "EU state-aid cases; recovered amounts vs originally foregone tax contested — Medium/Weak",
        8.0,
        7.0,
        "weak",
        "EC state-aid decisions on BE excess profit rulings",
        "Bespoke tax math for multinationals — until Brussels said no.",
        "Legal war years; fiscal opportunity cost real.",
    ),
    (
        "hw_union_unemp_admin",
        "Union unemployment payment admin grants (multi-year)",
        "2015–2025",
        "federal",
        "subsidy",
        "labour_market",
        1e9,
        1.7e9,
        2.2e9,
        "~€169m/yr class × 10y; middleman design",
        8.5,
        7.5,
        "strong",
        "DOGE lb_union_pay_admin_169m; middleman notes",
        "Unions paid to pay unemployment — a Belgian special.",
        "Steelman: proximity; waste is monopoly admin rent.",
    ),
    (
        "hw_charleroi_airport_aid",
        "Charleroi airport public support / Ryanair state-aid saga",
        "2000s–2010s",
        "Wallonia",
        "subsidy",
        "airports",
        0.1e9,
        0.3e9,
        0.8e9,
        "BSCA support + EC state-aid cases; multi-year — Medium/Weak",
        7.5,
        6.5,
        "weak",
        "EC Ryanair/Charleroi decisions; SOWAER notes",
        "Low-cost airport growth with a state-aid courtroom sequel.",
        "Jobs steelman; subsidy design was the problem.",
    ),
    (
        "hw_liege_airport_cargo",
        "Liège airport cargo growth public support stack",
        "2000s–2020s",
        "Wallonia",
        "subsidy",
        "airports",
        0.1e9,
        0.4e9,
        1e9,
        "Infrastructure + SOE support; noise externalities extra — Weak mid",
        7.0,
        5.5,
        "weak",
        "SOWAER; regional budgets; FOI candidates",
        "Cargo boom paid partly off the public balance sheet — and local sleep.",
        "Externalities under-priced.",
    ),
    (
        "hw_de_lijn_efficiency",
        "De Lijn multi-year dotatie efficiency gap (subset claim)",
        "2010s–2020s",
        "Flanders",
        "ops",
        "transport_opex",
        2e9,
        5e9,
        10e9,
        "Dotatie ~€1–1.5bn/yr; waste = efficiency gap only, not whole bus network — Weak split",
        5.0,
        3.0,
        "weak",
        "DOGE lb_de_lijn_dotatie; VL PQ series",
        "Buses are not waste; running them badly can be.",
        "Core service; KPI pressure is the reform.",
    ),
    (
        "hw_stib_efficiency",
        "STIB multi-year financing efficiency + Metro3 spillover",
        "2010s–2020s",
        "Brussels",
        "ops",
        "transport_opex",
        2e9,
        5e9,
        10e9,
        "~€1.2bn/yr class; efficiency + capital project spillover — Weak pure-waste split",
        5.0,
        3.0,
        "weak",
        "DOGE lb_stib; Cour BCR",
        "Dense city transit is valuable; blank cheques are not a strategy.",
        "Link to Metro3 governance.",
    ),
    (
        "hw_nmbs_pso_decade",
        "NMBS PSO / federal support package (10y class, efficiency subset)",
        "2015–2025",
        "federal",
        "ops",
        "transport_opex",
        15e9,
        20e9,
        25e9,
        "~€2bn/yr class × 10y; pure waste is inefficiency/ICT/punctuality gap not full PSO",
        5.0,
        3.0,
        "medium",
        "DOGE lb_nmbs_esa_support; ODC path",
        "Public rail needs public money — the waste is how much disappears into delay and IT.",
        "Rank high on cash, low on purity.",
    ),
    (
        "hw_health_low_value",
        "Low-value care / billing waste in health insurance (subset)",
        "2000s–2020s",
        "federal",
        "ops",
        "health",
        10e9,
        25e9,
        50e9,
        "RIZIV ~€40bn/yr; waste literature often 10–20% low-value care order-of-magnitude — Weak for BE-specific",
        6.0,
        5.0,
        "weak",
        "RIZIV budgets; international low-value care literature",
        "Universal care is a feature; paying for useless procedures is a bug.",
        "Do not campaign as cut to access; target low-value only.",
    ),
    (
        "hw_covid_untargeted",
        "COVID support packages — fraud + untargeted share",
        "2020–2022",
        "multi",
        "crisis_fiscal",
        "crisis_fiscal",
        5e9,
        15e9,
        30e9,
        "Total COVID fiscal multi-tens of bn; waste = fraud + clearly untargeted — Medium/Weak split",
        7.0,
        5.0,
        "weak",
        "NBB COVID fiscal; Court of Audit COVID support audits",
        "Emergency money that sometimes found the wrong pockets and the wrong firms.",
        "Speed steelman; design waste real.",
    ),
    (
        "hw_temporary_unemp_fraud",
        "Temporary unemployment / crisis unemployment fraud & overuse",
        "2020–2022",
        "federal",
        "transfer",
        "labour_market",
        0.5e9,
        2e9,
        5e9,
        "Subset of COVID labour support; fraud rates debated — Weak",
        8.0,
        7.0,
        "weak",
        "ONEM/RVA audits; press fraud series",
        "Furlough that became a lifestyle for some — detection lagged cash.",
        "Most use legitimate; fraud tail is waste.",
    ),
    (
        "hw_provincial_layer",
        "Provincial government layer ongoing cost (relevance debate)",
        "1830–2020s",
        "multi",
        "ops",
        "institutions",
        10e9,
        20e9,
        40e9,
        "VL+WAL provinces multi-bn/yr combined opex/invest; pure waste = redundant share only — Weak",
        7.0,
        5.0,
        "weak",
        "DOGE provincial snapshots 2026",
        "A middle layer of government looking for a job description since 1830.",
        "Some provincial services real; dual with communes/regions is the issue.",
    ),
    (
        "hw_cabinet_culture",
        "Ministerial cabinets culture — oversized political staff (multi-year)",
        "1990s–2020s",
        "multi",
        "admin",
        "institutions",
        1e9,
        3e9,
        6e9,
        "Cabinets vs administration dual staff; multi-year speculative — Weak",
        8.0,
        7.0,
        "weak",
        "DOGE seed board; governance literature BE",
        "A shadow civil service that leaves when the minister does — institutional amnesia included.",
        "Cap cabinets is a classic reform.",
    ),
    (
        "hw_waffle_iron_legacy",
        "Waffle-iron politics legacy capex (post-war compensatory spending pattern)",
        "1950s–1980s",
        "federal",
        "fiscal_architecture",
        "institutions",
        10e9,
        30e9,
        80e9,
        "Historical pattern of compensatory public works across communities; many GTI entries are symptoms — Weak aggregate",
        9.0,
        8.0,
        "weak",
        "Political science literature on waffle-iron; Defossé corpus as symptoms",
        "You get a tunnel because they got a bridge — Belgium’s original fiscal algorithm.",
        "Meta-entry explaining many ghost works.",
    ),
]


def main() -> int:
    rows = []
    for t in RAW:
        (
            _id,
            name,
            era,
            level,
            typ,
            category,
            cmin,
            cmid,
            cmax,
            basis,
            absu,
            purity,
            conf,
            sources,
            one_liner,
            notes,
        ) = t
        cs = cost_score(cmid)
        # waste_priority: cost + absurdity + purity (how 'pure waste' vs mixed public good)
        prio = round(0.45 * cs + 0.30 * absu + 0.25 * purity, 2)
        p = pain(cmid)
        rows.append(
            {
                "item_id": _id,
                "name": name,
                "era": era,
                "level": level,
                "type": typ,
                "category": category,
                "cost_min_eur": f"{cmin:.0f}" if cmin is not None else "",
                "cost_mid_eur": f"{cmid:.0f}" if cmid is not None else "",
                "cost_max_eur": f"{cmax:.0f}" if cmax is not None else "",
                "cost_basis": basis,
                "cost_score": f"{cs:.1f}",
                "absurdity_score": f"{absu:.1f}",
                "waste_purity": f"{purity:.1f}",
                "waste_priority": f"{prio:.2f}",
                "confidence": conf,
                **p,
                "sources_brief": sources,
                "one_liner": one_liner,
                "notes": notes,
            }
        )

    rows.sort(key=lambda r: (-float(r["waste_priority"]), -float(r["cost_mid_eur"] or 0)))
    for i, r in enumerate(rows, 1):
        r["rank"] = str(i)

    fields = [
        "rank",
        "item_id",
        "name",
        "era",
        "level",
        "type",
        "category",
        "cost_min_eur",
        "cost_mid_eur",
        "cost_max_eur",
        "cost_basis",
        "cost_score",
        "absurdity_score",
        "waste_purity",
        "waste_priority",
        "confidence",
        "pain_tax_fte",
        "pain_net_years",
        "pain_eur_per_employee",
        "pain_work_minutes",
        "sources_brief",
        "one_liner",
        "notes",
    ]
    DATA.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    write_md(rows)
    print(f"Wrote {len(rows)} rows → {OUT_CSV}")
    print(f"Wrote markdown → {OUT_MD}")
    return 0


def write_md(rows: list[dict]) -> None:
    top = rows  # all
    lines = []
    lines.append("# Belgium Historical Waste Hall of Fame (Top 100)")
    lines.append("")
    lines.append("**Sister board to DOGE (current spend) and Proposal Radar (new ideas).**  ")
    lines.append("This board scores **past and multi-year** public money disasters: ghost infrastructure, bailouts, IT flops, structural tax expenditures, and policy design failures.")
    lines.append("")
    lines.append("| | |")
    lines.append("|--|--|")
    lines.append("| **As-of** | 2026-07-27 seed v1 |")
    lines.append(f"| **Entries** | {len(rows)} |")
    lines.append("| **Data** | [`data/historical_waste_hall.csv`](data/historical_waste_hall.csv) |")
    lines.append("| **Pain unit** | Same as Proposal Radar `taxpayer_unit` v2 |")
    lines.append("| **Honesty** | Ranges + confidence; **not** audited campaign claims |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## What this is (and is not)")
    lines.append("")
    lines.append("| This is | This is not |")
    lines.append("|---------|-------------|")
    lines.append("| A **research seed** of Belgium’s most expensive bad decisions | A claim that every euro was illegal |")
    lines.append("| Ranked by **waste_priority** = 0.45×cost_score + 0.30×absurdity + 0.25×purity | Pure size ranking of all public spend |")
    lines.append("| Pain columns: how much **work** funds the mid € estimate | Precision finer than the underlying € confidence |")
    lines.append("| Mix of ghost tunnels **and** multi-year taxex / bailouts / laws | Only ‘funny bridges’ tourism |")
    lines.append("")
    lines.append("**Steelman rule:** many large rows are *mixed* public goods with a waste *component* (e.g. rail PSO, nuclear policy). `waste_purity` captures that. High cash + low purity still ranks — but notes say so.")
    lines.append("")
    lines.append("**Do not sum the column.** Many multi-year structural rows overlap (company cars ⊂ taxex total; PV boom ⊂ GSC; etc.).")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Taxpayer pain (same metrics as Proposal Radar)")
    lines.append("")
    lines.append("| Column | Meaning |")
    lines.append("|--------|---------|")
    lines.append("| **Belasting-FTE** (`pain_tax_fte`) | Mid public € ÷ €19,400 = how many average workers’ **full yearly labour-tax bill** |")
    lines.append("| **Nettoloon-jaren** (`pain_net_years`) | Mid public € ÷ €29,500 = years of one person’s **take-home pay** |")
    lines.append("| **Werkminuten** (`pain_work_minutes`) | If split across **all ~4.85m** Belgian employees: minutes of work **each** put in |")
    lines.append("")
    lines.append("Unit: average single FT employee; OECD Taxing Wages-style labour tax; see [`../proposal-radar/TAXPAYER_UNIT.md`](../proposal-radar/TAXPAYER_UNIT.md).")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Ranking formula")
    lines.append("")
    lines.append("```text")
    lines.append("cost_score bands (mid €): <1m→1.5 · <10m→3.5 · <100m→5.5 · <1bn→7.5 · ≥1bn→9.5")
    lines.append("waste_priority = 0.45×cost_score + 0.30×absurdity + 0.25×waste_purity")
    lines.append("```")
    lines.append("")
    lines.append("| Score | Meaning |")
    lines.append("|-------|---------|")
    lines.append("| **Absurdity** 1–10 | Goal failure, perverse incentives, capture, complexity theatre |")
    lines.append("| **Waste purity** 1–10 | 10 = pure boondoggle / failed IT; 3 = large mixed public good with efficiency gap |")
    lines.append("| **Confidence** | strong / medium / weak on the euro mid-point |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Top 25 by waste_priority (headline)")
    lines.append("")
    lines.append("| # | Name | Era | Mid € | Abs | Pur | **Prio** | Belasting-FTE | Werkminuten/employee | Conf |")
    lines.append("|--:|------|-----|------:|----:|----:|---------:|--------------:|---------------------:|:----:|")
    for r in top[:25]:
        lines.append(
            f"| {r['rank']} | {r['name'][:70]} | {r['era']} | {fmt_eur(float(r['cost_mid_eur']))} | {r['absurdity_score']} | {r['waste_purity']} | **{r['waste_priority']}** | {float(r['pain_tax_fte']):,.0f} | {fmt_min(r['pain_work_minutes'])} | {r['confidence'][0].upper()} |"
        )
    lines.append("")
    lines.append("### Also: Top 15 by mid € (size, not purity)")
    lines.append("")
    by_cash = sorted(rows, key=lambda r: -float(r["cost_mid_eur"] or 0))[:15]
    lines.append("| Mid € | Name | Abs | Pur | Prio rank | Werkminuten/employee |")
    lines.append("|------:|------|----:|----:|----------:|---------------------:|")
    for r in by_cash:
        lines.append(
            f"| {fmt_eur(float(r['cost_mid_eur']))} | {r['name'][:55]} | {r['absurdity_score']} | {r['waste_purity']} | #{r['rank']} | {fmt_min(r['pain_work_minutes'])} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Full ranked list (all entries)")
    lines.append("")
    lines.append("| # | Name | Category | Level | Mid € | Abs | Pur | Prio | Belasting-FTE | Nettoloon-jaren | Werkminuten | €/employee | Conf | One-liner |")
    lines.append("|--:|------|----------|-------|------:|----:|----:|-----:|--------------:|----------------:|------------:|-----------:|:----:|-----------|")
    for r in top:
        lines.append(
            f"| {r['rank']} | {r['name'][:55]} | {r['category']} | {r['level']} | {fmt_eur(float(r['cost_mid_eur']))} | {r['absurdity_score']} | {r['waste_purity']} | {r['waste_priority']} | {float(r['pain_tax_fte']):,.0f} | {float(r['pain_net_years']):,.0f} | {fmt_min(r['pain_work_minutes'])} | €{float(r['pain_eur_per_employee']):,.0f} | {r['confidence'][0].upper()} | {r['one_liner'][:80]} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Gallery: pure boondoggles (high purity, not always top cash)")
    lines.append("")
    pure = sorted(rows, key=lambda r: (-float(r["waste_purity"]), -float(r["absurdity_score"])))[:20]
    lines.append("| Name | Mid € | Abs | Pur | Werkminuten | Why iconic |")
    lines.append("|------|------:|----:|----:|------------:|------------|")
    for r in pure:
        lines.append(
            f"| {r['name'][:60]} | {fmt_eur(float(r['cost_mid_eur']))} | {r['absurdity_score']} | {r['waste_purity']} | {fmt_min(r['pain_work_minutes'])} | {r['one_liner'][:90]} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Categories covered")
    lines.append("")
    cats: dict[str, int] = {}
    for r in rows:
        cats[r["category"]] = cats.get(r["category"], 0) + 1
    lines.append("| Category | n |")
    lines.append("|----------|--:|")
    for k, v in sorted(cats.items(), key=lambda x: -x[1]):
        lines.append(f"| `{k}` | {v} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Media one-liners (pain unit)")
    lines.append("")
    # pick some iconic ones by id
    want = {
        "hw_i_police",
        "hw_metro3_bru",
        "hw_smeerpijp",
        "hw_oosterweel",
        "hw_company_cars_decade",
        "hw_cheque_economy_decade",
        "hw_smaakhaven",
        "hw_bank_bailouts_2008_12",
        "hw_thuin_internat",
        "hw_charleroi_mlc",
    }
    for r in rows:
        if r["item_id"] not in want:
            continue
        lines.append(
            f"- **{r['name'][:50]}** ({fmt_eur(float(r['cost_mid_eur']))} mid): "
            f"~**{float(r['pain_tax_fte']):,.0f} Belasting-FTE** · "
            f"~**{float(r['pain_net_years']):,.0f} nettoloon-jaren** · "
            f"**{fmt_min(r['pain_work_minutes'])}** per employee if split."
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Method & sources")
    lines.append("")
    lines.append("1. **GTI corpus** — Jean-Claude Defossé *Grands Travaux Inutiles* / RTBF JTI; [fr.wiki list](https://fr.wikipedia.org/wiki/Liste_de_grands_travaux_inutiles_en_Belgique); Hidden Monuments boondoggle map.")
    lines.append("2. **Fiscal inventories** — FPS tax expenditures, FFS fossil inventory, NBB enterprise subsidies (linked to DOGE leaderboard rows).")
    lines.append("3. **Crisis / bailouts** — 2008–12 Fortis/Dexia/KBC public capital paths; Sabena; COVID support audits.")
    lines.append("4. **Modern mega-projects** — Oosterweel Rekenhof/press 2026; Metro 3 Cour des comptes; Liège tram; i-Police 2026.")
    lines.append("5. **Institutions** — dual PSB, multi-PES, provinces, cabinets, waffle-iron meta-pattern.")
    lines.append("")
    lines.append("Primary sources preferred when € is **strong**; press + secondary when **medium/weak**. Upgrade path: attach Court of Audit report IDs + FOI for unconsolidated historical GTI bills.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Corrections log")
    lines.append("")
    lines.append("| Date | Item | Change |")
    lines.append("|------|------|--------|")
    lines.append("| 2026-07-27 | — | v1 seed published |")
    lines.append("")
    lines.append("Wrong entries get **struck with date + reason**, same discipline as DOGE.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Links")
    lines.append("")
    lines.append("- Current spend: [`06-doge-belgium.md`](../06-doge-belgium.md) · [`data/doge_waste_top10_current.md`](data/doge_waste_top10_current.md)")
    lines.append("- New proposals: [`09-proposal-radar.md`](../09-proposal-radar.md) · pain unit [`../proposal-radar/TAXPAYER_UNIT.md`](../proposal-radar/TAXPAYER_UNIT.md)")
    lines.append("- Rebuild script: [`scripts/build_historical_waste_hall.py`](scripts/build_historical_waste_hall.py)")
    lines.append("")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
