# tick 344 — Wallimage + Screen Flanders dual economic AV funds (rq_335)
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
now = "2026-07-31T10:45:00Z"
tick = 344
unit = "rq_335"

# --- sources ---
with open(root / "sources.csv", "a", encoding="utf-8") as f:
    f.write(
        "src_wallimage_bilan_2024,Wallimage Bilan des activites 2024 Coproductions Entreprises Gaming,"
        "https://www.wallimage.be/wp-content/uploads/2025/03/wallimagebilan2024.pdf,"
        "Wallimage SA,2026-07-31,official_annual_report,"
        "Strong: Coproductions invest 7.0948m 2024 retombees 46.232m; Entreprises validated 3.72m; "
        "volant 6.5m since 2018; dual Screen Flanders; tick344\n"
    )
    f.write(
        "src_wallimage_bilan_2025,Wallimage Bilan des activites 2025 Coproductions Entreprises,"
        "https://www.wallimage.be/wp-content/uploads/2026/03/wallimagebilan2025.pdf,"
        "Wallimage SA,2026-07-31,official_annual_report,"
        "Strong: Coproductions invest 6.686375m 2025 retombees 51.436m ratio 769pct; "
        "Entreprises 4.1913m 19 deals; stock 10.23m; dual SF; tick344\n"
    )
    f.write(
        "src_vaf_screen_flanders_page,VAF Screen Flanders economisch fonds Hermes 3.5m annual,"
        "https://www.vaf.be/screenflanders,"
        "VAF / VLAIO,2026-07-31,official_agency_page,"
        "Strong: VLAIO annual budget Screen Flanders 3.500.000 EUR Hermesfonds; max 400k recoupable; "
        "dual Wallimage economic AV; tick344\n"
    )
    f.write(
        "src_wallimage_gaming_2026,Wallimage Gaming 2m annual fund 2026,"
        "https://www.wallimage.be/en/services/wallimage-gaming/,"
        "Wallimage SA,2026-07-31,official_agency_page,"
        "Strong: Gaming budget 2m EUR allocated Oct 2025 for FY2026; dual VAF Gamefonds; tick344\n"
    )

# --- entities ---
with open(root / "entities.csv", "a", encoding="utf-8") as f:
    f.write(
        "wallimage,Wallimage SA economisch audiovisueel fonds Wallonie,"
        "Wallimage SA fonds economique audiovisuel wallon,"
        "Walloon economic audiovisual and gaming fund (coproductions + entreprises + gaming),"
        "agency,wallonie_gov,fr,https://www.wallimage.be,,,,"
        "Coprod 7.09m 2024 / 6.69m 2025; Entreprises 3.72/4.19m; dual Screen Flanders; tick344\n"
    )
    f.write(
        "screen_flanders,Screen Flanders economisch AV fonds VLAIO Hermes,"
        "Screen Flanders fonds economique audiovisuel Flandre,"
        "Flanders economic audiovisual fund VLAIO Hermes budget administered with VAF,"
        "agency,vlaio,nl,https://www.vaf.be/screenflanders,,,,"
        "Annual 3.5m Hermes; dual Wallimage; VAF culture separate; tick344\n"
    )

# --- budgets ---
# Coprod 2024 7094800; spend 46231969.51
# Entreprises 2024 3719964.29
# Sum economic invest class 2024: 7094800+3719964 ≈ 10814764
# Coprod 2025 6686375; spend 51435708.57
# Entreprises 2025 4191300
# Sum 2025: 6686375+4191300 = 10877675
# Gaming 2026 budget 2000000
# Screen Flanders annual 3500000
# Volant production 6500000 (capacity since 2018)
# Stock Entreprises 2024-end 13590580; 2025-end 10232766
# Gaming cumulative to 2024 from bilan p88: 3806274.31 (since launch preprod+prod) — label carefully
bud_rows = [
    "bud_wallimage_coprod_invest_2024,wallimage,2024,7094800,,,outturn,src_wallimage_bilan_2024,strong,"
    "Wallimage Coproductions total investment 7.0948m 2024 (49 projects) bilan ch.7.1",
    "bud_wallimage_coprod_spend_wal_2024,wallimage,2024,46231970,,,outturn,src_wallimage_bilan_2024,strong,"
    "Walloon spend generated by Wallimage coproductions 46.232m 2024 ratio ~652pct",
    "bud_wallimage_entreprises_invest_2024,wallimage,2024,3719964,,,outturn,src_wallimage_bilan_2024,strong,"
    "Wallimage Entreprises 12 validated investments total 3.719964m 2024",
    "bud_wallimage_economic_invest_sum_2024,wallimage,2024,10814764,,,outturn,src_wallimage_bilan_2024,strong,"
    "Sum Coprod+Entreprises annual invest 7.095+3.720=10.815m 2024 (excl Gaming multi-year stock)",
    "bud_wallimage_entreprises_stock_2024,wallimage,2024,13590580,,,outturn,src_wallimage_bilan_2024,strong,"
    "Wallimage Entreprises portfolio stock end-2024 13.591m (46 companies capital+loans)",
    "bud_wallimage_coprod_invest_2025,wallimage,2025,6686375,,,outturn,src_wallimage_bilan_2025,strong,"
    "Wallimage Coproductions total investment 6.686375m 2025 (47 projects) bilan",
    "bud_wallimage_coprod_spend_wal_2025,wallimage,2025,51435709,,,outturn,src_wallimage_bilan_2025,strong,"
    "Walloon spend generated by Wallimage coproductions 51.436m 2025 ratio 769pct record",
    "bud_wallimage_entreprises_invest_2025,wallimage,2025,4191300,,,outturn,src_wallimage_bilan_2025,strong,"
    "Wallimage Entreprises 19 validated investments total 4.1913m 2025",
    "bud_wallimage_economic_invest_sum_2025,wallimage,2025,10877675,,,outturn,src_wallimage_bilan_2025,strong,"
    "Sum Coprod+Entreprises annual invest 6.686+4.191=10.878m 2025",
    "bud_wallimage_entreprises_stock_2025,wallimage,2025,10232766,,,outturn,src_wallimage_bilan_2025,strong,"
    "Wallimage Entreprises portfolio stock end-2025 10.233m (40 companies; bankruptcies reduced stock)",
    "bud_wallimage_volant_prod_annual,wallimage,2024,6500000,,,budgeted,src_wallimage_bilan_2024,strong,"
    "Annual production investment capacity volant 6.5m since 2018 (foreword bilan 2024)",
    "bud_wallimage_gaming_budget_2026,wallimage,2026,2000000,,,budgeted,src_wallimage_gaming_2026,strong,"
    "Wallimage Gaming annual fund 2.0m EUR for FY2026 (minister allocation Oct 2025)",
    "bud_wallimage_gaming_cumul_preprod_prod,wallimage,2024,3806274,,,outturn,src_wallimage_bilan_2024,medium,"
    "Gaming preprod+prod cumulative engagements 3.806m generating 14.500m Walloon spend (since launch to bilan 2024)",
    "bud_screen_flanders_annual_budget,screen_flanders,2025,3500000,,,budgeted,src_vaf_screen_flanders_page,strong,"
    "Screen Flanders annual budget 3.5m EUR from VLAIO Hermesfonds (VAF page; ongoing rate)",
    "bud_av_econ_dual_sf_wallimage_class_2024,wallimage,2024,14314764,,,budgeted,src_wallimage_bilan_2024,medium,"
    "Illustrative dual economic AV class Wallimage Coprod+Ent 10.815m + Screen Flanders 3.5m ~14.3m 2024 not additive TE",
]
with open(root / "budgets.csv", "a", encoding="utf-8") as f:
    f.write("\n".join(bud_rows) + "\n")


def cmt(cid, title, eid, ben, legal, ddate, sy, ey, tot, cash, rem, url, goal, cut, src, conf, path, notes):
    cf = json.dumps(cash, separators=(",", ":")).replace('"', '""')
    rem_s = "" if rem is None else str(rem)
    return (
        f'{cid},{title},{eid},{ben},{legal},{ddate},{sy},{ey},{tot},'
        f'"{cf}",{rem_s},active,{url},{goal},{cut},{src},{conf},{path},{notes}\n'
    )


with open(root / "commitments.csv", "a", encoding="utf-8") as f:
    f.write(
        cmt(
            "cmt_wallimage_economic_av_2024_25",
            "Wallimage economic AV coproductions+entreprises dual Screen Flanders",
            "wallimage",
            "Walloon AV producers companies gaming studios",
            "Walloon economic fund Wallimage SA public investment",
            "2024-01-01",
            2024,
            2025,
            21692439,
            {
                "coprod_invest_2024": 7094800,
                "entreprises_invest_2024": 3719964,
                "sum_2024": 10814764,
                "coprod_invest_2025": 6686375,
                "entreprises_invest_2025": 4191300,
                "sum_2025": 10877675,
                "coprod_spend_wal_2024": 46231970,
                "coprod_spend_wal_2025": 51435709,
                "entreprises_stock_eoy2024": 13590580,
                "entreprises_stock_eoy2025": 10232766,
                "volant_prod_m": 6.5,
                "gaming_budget_2026": 2000000,
                "screen_flanders_annual": 3500000,
                "note": "Investments recoupable/participating not pure grants; dual Screen Flanders Hermes 3.5m; dual VAF/CCA culture separate",
            },
            None,
            "https://www.wallimage.be/wp-content/uploads/2026/03/wallimagebilan2025.pdf",
            "Develop sustain Walloon audiovisual and gaming industries",
            "Publish L5 named project/company awards; dual unit-cost Screen Flanders; map public capital injection path",
            "src_wallimage_bilan_2025",
            "strong",
            "Wallonia>Economy>Wallimage",
            "tick344: dual economic AV vs Screen Flanders vs VAF/CCA culture",
        )
    )
    f.write(
        cmt(
            "cmt_screen_flanders_hermes_3p5m",
            "Screen Flanders VLAIO Hermes economic AV fund 3.5m annual dual Wallimage",
            "screen_flanders",
            "Audiovisual productions spending in Flanders Region",
            "VLAIO Hermesfonds Screen Flanders measure via VAF administration",
            "2021-01-01",
            2024,
            2026,
            10500000,
            {
                "annual_budget": 3500000,
                "max_per_production": 400000,
                "form": "recoupable advances",
                "calls_per_year": 2,
                "dual_wallimage_coprod_2024_m": 7.095,
                "dual_wallimage_sum_2024_m": 10.815,
                "note": "3-year illustrative envelope 3x3.5m; rate from VAF official page not multi-year decree extract",
            },
            None,
            "https://www.vaf.be/screenflanders",
            "Attract AV spend and production to Flanders Region",
            "Publish annual award list L5; dual Wallimage comparison; Hermes cash path FOI if budget line opaque",
            "src_vaf_screen_flanders_page",
            "strong",
            "Flanders>VLAIO>ScreenFlanders",
            "tick344: 3.5m Hermes dual Wallimage economic AV",
        )
    )

# --- leaderboard ---
# priority_index style: modest absurdity (economic funds with claimed high return ratios)
with open(root / "leaderboard.csv", "a", encoding="utf-8") as f:
    f.write(
        "lb_wallimage_coprod_7m,Wallimage Coproductions economic AV invest ~7m/yr dual SF,"
        "regional,subsidy,Wallonia>Economy>Wallimage_Coprod,7094800,13781175,"
        "Strong bilan: 7.095m 2024 + 6.686m 2025 invest; retombees 46-51m claimed; dual Screen Flanders 3.5m,"
        "strong,src_wallimage_bilan_2025,Walloon AV producers coproductions,"
        "Regional economic development audiovisual spend,"
        "High claimed leverage ratios; recoupable investments not pure grants; dual culture VAF/CCA separate,"
        "4,5.5,5,5.0,"
        "Publish named project L5 + recoup rates; dual SF transparency,"
        "seed,,tick344 dual economic AV\n"
    )
    f.write(
        "lb_screen_flanders_3p5m,Screen Flanders Hermes economic AV 3.5m dual Wallimage,"
        "regional,subsidy,Flanders>VLAIO>ScreenFlanders,3500000,3500000,"
        "Strong VAF page: annual 3.5m Hermes; max 400k recoupable advances; dual Wallimage ~7-11m class,"
        "strong,src_vaf_screen_flanders_page,Productions spending in Flanders,"
        "Attract film TV production spend to Flanders,"
        "Small vs culture funds+tax shelter; dual regional economic layer on top of VAF/CCA/TS,"
        "3,4.0,4,3.7,"
        "Open L5 awards list; Hermes budget line multi-year,"
        "seed,,tick344 dual Wallimage\n"
    )
    f.write(
        "lb_av_econ_dual_wallimage_sf,Dual economic AV Wallimage+Screen Flanders class ~14m,"
        "regional,subsidy,BE>dual>AV_economic_funds,14300000,14300000,"
        "Medium class: Wallimage Coprod+Ent ~10.8m 2024 + SF 3.5m ~14.3m; not additive TE; culture dual separate,"
        "medium,src_wallimage_bilan_2024,Regional AV industries both communities,"
        "Dual-structure economic film incentives Flanders/Wallonia,"
        "Classic dual overhead pattern: two economic funds + two culture funds + federal tax shelter,"
        "5,6.0,5,5.5,"
        "Map full AV stack TCO culture+economic+TE; FOI L5 both funds,"
        "seed,,tick344 dual structure\n"
    )

# --- FOI ---
gap_id = "gap_wallimage_sf_econ_l5"
draft_path = Path(__file__).resolve().parents[2] / "foi" / "drafts" / f"{gap_id}.md"
draft_path.parent.mkdir(parents=True, exist_ok=True)
draft_path.write_text(
    f"""# FOI draft — {gap_id}

Status: **ready** (human send only)

## Brief

```text
[Naam verzoeker]
[Adres / e-mail / telefoon]
[Datum]

Aan: Wallimage SA / Service public de Wallonie — Économie
cc: VLAIO / Screen Flanders (via VAF) — openbaarheid@vlaanderen.be
     Hermesfonds / Departement WEWIL waar van toepassing

Betreft: Verzoek om openbaarmaking — Wallimage / Screen Flanders economische AV-steun L5 dual

Geachte,

Op grond van de toepasselijke openbaarheidsregels (Wallonië: décret transparence;
Vlaanderen: Bestuursdecreet) vraag ik:

1. **Wallimage Coproductions**: machineleesbare lijst toegekende investeringen
   2023-2025 met bedrag, project/titel, begunstigde productiemaatschappij,
   type (LM/serie/doc/flux/anim), recoup status.
2. **Wallimage Entreprises**: lijst investeringen/kapitaal/leningen 2023-2025
   met bedrag, vennootschap, instrument (equity/loan), en-cours EOY.
3. **Wallimage Gaming**: toegekende preproductie/productie 2023-2026 vs
   budgetlijn (o.a. 2 m EUR 2026).
4. **Screen Flanders / VLAIO Hermes**: jaarlijkse kas/begrotingslijn 2022-2026
   en top-20 toegekende voorschotten met bedrag, project, begunstigde.
5. Eventuele **publieke kapitaalinjecties / dotaties** van het Waalse Gewest
   of Vlaamse Hermesfonds naar deze fondsen (cash-by-year).

Publiek (primaire bronnen tick344):
- Wallimage Coprod invest **€7,094,800** (2024) / **€6,686,375** (2025);
  retombées wallonnes **€46.2 m** / **€51.4 m**.
- Wallimage Entreprises **€3.72 m** (2024) / **€4.19 m** (2025).
- Screen Flanders jaarlijks **€3.5 m** (Hermes/VLAIO; VAF-pagina).
- Dual culture stack apart: VAF ~€30.7 m + CCA >€44 m + Tax Shelter TE.

Dossierreferentie intern: {gap_id}

Met vriendelijke groet,
[Naam]
```

## Checklist
- [x] Wallimage + SPW Économie / VLAIO Hermes / VL openbaarheid
- [x] Concrete L5 dual economic AV map
- [x] foi_queue ready
- [ ] Human send

## Public fill tick344

Sources: Wallimage Bilan 2024 PDF; Bilan 2025 PDF; VAF Screen Flanders page; Wallimage Gaming page.

Residual FOI: named award matrices + Hermes cash path + public capital injections.
""",
    encoding="utf-8",
)

with open(root / "foi_queue.csv", "a", encoding="utf-8") as f:
    f.write(
        f"{gap_id},Wallonia+Flanders>Economy>Wallimage_ScreenFlanders_L5,wallimage,"
        "Named L5 awards Wallimage Coprod/Entreprises/Gaming + Screen Flanders Hermes cash path and top awards,"
        "Dual economic AV funds opacity under culture dual VAF/CCA + federal Tax Shelter stack,"
        "5,Wallimage SA / SPW Economie + VLAIO Hermes,"
        "info@wallimage.be; openbaarheid@vlaanderen.be,,"
        f"docs/doge/foi/drafts/{gap_id}.md,ready,2026-07-31,,,,,"
        f"cmt_wallimage_economic_av_2024_25,lb_av_econ_dual_wallimage_sf,"
        f"{now},{now},"
        "tick344 public fill bilans; residual L5 human send\n"
    )

# --- research_queue: close rq_335, spawn rq_336 ---
rq_path = root / "research_queue.csv"
text = rq_path.read_text(encoding="utf-8")
# close rq_335
old_335 = (
    "rq_335,Continuous FOI-adjacent public hole-fill batch,continuous,5,open,L5,gg_belgium,"
    "Prefer public primary fills (FOI-adjacent dual/L5). Prefer before idle.,,"
    "2026-07-31T10:15:00Z,,Spawned tick343 after Tax Shelter TE dual culture; rq_116 SWA deferred"
)
new_335 = (
    f"rq_335,Continuous FOI-adjacent public hole-fill batch,continuous,5,done,L5,gg_belgium,"
    f"Prefer public primary fills (FOI-adjacent dual/L5). Prefer before idle.,{gap_id},"
    f"2026-07-31T10:15:00Z,{now},"
    "tick344: Wallimage Coprod 7.09m/6.69m + Ent 3.72/4.19m dual Screen Flanders 3.5m; FOI L5; spawn rq_336"
)
if old_335 not in text:
    # fuzzy replace by line start
    lines = text.splitlines(keepends=True)
    out = []
    found = False
    for line in lines:
        if line.startswith("rq_335,") and ",open," in line:
            out.append(new_335 + ("\n" if not new_335.endswith("\n") else ""))
            if not out[-1].endswith("\n"):
                out[-1] += "\n"
            found = True
        else:
            out.append(line)
    if not found:
        raise SystemExit("rq_335 open row not found")
    text = "".join(out)
else:
    text = text.replace(old_335, new_335)

# spawn rq_336
if "rq_336," not in text:
    if not text.endswith("\n"):
        text += "\n"
    text += (
        "rq_336,Continuous FOI-adjacent public hole-fill batch,continuous,5,open,L5,gg_belgium,"
        "Prefer public primary fills (FOI-adjacent dual/L5). Prefer before idle.,,"
        f"{now},,Spawned tick344 after Wallimage+Screen Flanders dual economic AV; rq_116 SWA deferred\n"
    )
rq_path.write_text(text, encoding="utf-8")

# --- loop_state ---
(root / "loop_state.csv").write_text(
    "state_id,mode,current_sprint,last_tick_utc,last_unit_id,ticks_completed,paused,notes\n"
    f"main,continuous,hole_fill,{now},{unit},{tick},no,"
    "Scheduler 60s. Next prio5 rq_336; rq_116 SWA deferred. FOI ready. tick344 Wallimage+SF dual econ AV.\n",
    encoding="utf-8",
)

# --- loop_log append ---
log_path = Path(__file__).resolve().parents[2] / "loop_log.md"
entry = f"""
### {now} - tick {tick}
- Unit: **{unit}** (FOI-adjacent hole-fill - **Wallimage + Screen Flanders dual economic AV**)
- Found (strong Wallimage Bilan 2024/2025 PDF + VAF Screen Flanders page + Gaming page):
  - **Wallimage Coproductions invest:** **€7.0948m** 2024 (49 projects) · **€6.686m** 2025 (47 projects).
  - **Walloon spend generated:** **€46.232m** 2024 (~652%) · **€51.436m** 2025 (**769%** record).
  - **Wallimage Entreprises:** **€3.720m** (12 deals 2024) · **€4.191m** (19 deals 2025); stock **€13.59m** EOY24 → **€10.23m** EOY25.
  - **Production volant** capacity **€6.5m/yr** since 2018; **Gaming** FY2026 budget **€2.0m**.
  - **Screen Flanders:** VLAIO Hermes **€3.5m/yr**; max **€400k** recoupable advances; VAF admin.
  - Dual stack: economic (Wallimage~€10.8m + SF €3.5m) on top of culture (VAF ~€30.7m + CCA >€44m) + federal Tax Shelter TE.
- Wrote: sources +4; entities +2; budgets +15; cmt +2; lb +3; FOI {gap_id} ready; rq_335=done; spawn rq_336; ticks={tick}
- FOI: named awards L5 both funds + Hermes cash path ready human send
- Next: prio5 **rq_336**; deferred **rq_116** SWA
"""
with open(log_path, "a", encoding="utf-8") as f:
    f.write(entry)

print(f"tick {tick} unit {unit} wrote OK")
print(f"FOI draft: {draft_path}")
